import { CandidateProfile, CandidateRating, EmployerProfile, EmployerRating } from "./types";

// =============================================
// MOCK CANDIDATES
// =============================================

export const MOCK_CANDIDATES: (Partial<CandidateProfile> & { name: string; rating: CandidateRating })[] = [
  {
    name: "Алия",
    userId: "candidate_aliya",
    preferredCategories: ["HoReCa", "Retail"],
    categoryInterests: [
      { category: "HoReCa", intensity: "high", subRoles: ["бариста", "официант"] },
      { category: "Retail", intensity: "medium", subRoles: ["продавец"] },
    ],
    employmentTypes: ["Подработка", "Сменный график"],
    skills: [
      { name: "Коммуникабельность", group: "soft", level: "confident" },
      { name: "Обслуживание клиентов", group: "service", level: "basic" },
      { name: "Работа с кассой", group: "service", level: "beginner" },
    ],
    customSkills: [],
    languages: [
      { language: "Казахский", level: "conversational", canServeCustomers: true, canWriteMessages: false, canInterview: true },
      { language: "Русский", level: "fluent", canServeCustomers: true, canWriteMessages: true, canInterview: true },
      { language: "English", level: "basic", canServeCustomers: false, canWriteMessages: false, canInterview: false },
    ],
    hasExperience: false,
    workExperiences: [],
    volunteerExperience: "Волонтёр на школьных мероприятиях",
    readyToday: true,
    preferredDistricts: ["14 мкр", "12 мкр"],
    salaryExpectation: 150000,
    acceptsTrialShift: true,
    wantsFirstJobFriendly: true,
    aiSummary: "Алия — студентка из 14 мкр, ищет part-time работу после 16:00 в HoReCa или Retail. Подходит для beginner-friendly вакансий, умеет общаться с клиентами на русском и казахском.",
    aiHeadline: "Студентка · Начинающий специалист · 14 мкр",
    experienceLevel: "Без опыта",
    completenessScore: 72,
    rating: {
      workScore: 72,
      level: "ready",
      responseRate: 88,
      completedInterviews: 1,
      completedShifts: 0,
      employerFeedbackAvg: 0,
      noShowCount: 0,
      badges: [
        { id: "ready_today", title: "Готов сегодня", icon: "⚡" },
        { id: "no_exp_friendly", title: "Без опыта", icon: "🌱" },
        { id: "customer_comm", title: "Основы обслуживания", icon: "💬" },
      ],
      scoreBreakdown: {
        profileCompleteness: 20, languagesAdded: 10, availabilityAdded: 10,
        cvOrAiSummary: 10, fastResponse: 10, completedInterview: 7,
        positiveFeedback: 5, noShowPenalty: 0,
      },
    },
  },
  {
    name: "Данияр",
    userId: "candidate_daniyar",
    preferredCategories: ["Retail", "Service"],
    categoryInterests: [
      { category: "Retail", intensity: "high", subRoles: ["консультант", "кассир"] },
      { category: "Service", intensity: "medium", subRoles: ["администратор"] },
    ],
    employmentTypes: ["Полная занятость"],
    skills: [
      { name: "Продажи", group: "service", level: "confident" },
      { name: "Ответственность", group: "soft", level: "experienced" },
      { name: "ПК грамотность", group: "digital", level: "basic" },
      { name: "Стрессоустойчивость", group: "soft", level: "confident" },
    ],
    customSkills: [],
    languages: [
      { language: "Русский", level: "fluent", canServeCustomers: true, canWriteMessages: true, canInterview: true },
      { language: "Казахский", level: "fluent", canServeCustomers: true, canWriteMessages: true, canInterview: true },
    ],
    hasExperience: true,
    workExperiences: [
      { role: "Продавец-консультант", workplace: "Магазин электроники", duration: "6 месяцев", responsibilities: "Консультирование, выкладка товара", achievements: "Лучший продавец месяца" },
    ],
    readyToday: false,
    preferredDistricts: ["29 мкр", "27 мкр"],
    salaryExpectation: 200000,
    acceptsTrialShift: true,
    wantsFirstJobFriendly: false,
    aiSummary: "Данияр — опытный продавец-консультант из 29 мкр. Свободно владеет казахским и русским, имеет реальный опыт розничных продаж. Надёжный и ответственный.",
    aiHeadline: "Продавец-консультант · Опыт 6 мес. · 29 мкр",
    experienceLevel: "Есть опыт",
    completenessScore: 84,
    rating: {
      workScore: 84,
      level: "reliable",
      responseRate: 95,
      completedInterviews: 3,
      completedShifts: 2,
      employerFeedbackAvg: 4.5,
      noShowCount: 0,
      badges: [
        { id: "profile_complete", title: "Профиль заполнен", icon: "✅" },
        { id: "retail_exp", title: "Опыт в Retail", icon: "🛒" },
        { id: "reliable", title: "Надёжный откликатор", icon: "🎯" },
      ],
      scoreBreakdown: {
        profileCompleteness: 20, languagesAdded: 10, availabilityAdded: 10,
        cvOrAiSummary: 10, fastResponse: 10, completedInterview: 15,
        positiveFeedback: 9, noShowPenalty: 0,
      },
    },
  },
  {
    name: "Мадина",
    userId: "candidate_madina",
    preferredCategories: ["Service", "Beauty"],
    categoryInterests: [
      { category: "Service", intensity: "high", subRoles: ["администратор"] },
      { category: "Beauty", intensity: "open", subRoles: ["помощник мастера"] },
    ],
    employmentTypes: ["Работа на выходных", "Подработка"],
    skills: [
      { name: "Пунктуальность", group: "soft", level: "experienced" },
      { name: "Вежливость", group: "soft", level: "confident" },
      { name: "Соцсети", group: "digital", level: "confident" },
    ],
    customSkills: ["Instagram продвижение"],
    languages: [
      { language: "Казахский", level: "native", canServeCustomers: true, canWriteMessages: true, canInterview: true },
      { language: "Русский", level: "conversational", canServeCustomers: true, canWriteMessages: false, canInterview: true },
    ],
    hasExperience: false,
    workExperiences: [],
    volunteerExperience: "Помощь на семейных мероприятиях",
    readyToday: false,
    preferredDistricts: ["12 мкр", "11 мкр"],
    salaryExpectation: 120000,
    acceptsTrialShift: true,
    wantsFirstJobFriendly: true,
    aiSummary: "Мадина — ищет работу на выходных в сфере обслуживания или бьюти. Казахский — родной, русский — разговорный. Пунктуальна и вежлива, готова к пробной смене.",
    aiHeadline: "Администратор · Выходные · 12 мкр",
    experienceLevel: "Без опыта",
    completenessScore: 68,
    rating: {
      workScore: 68,
      level: "ready",
      responseRate: 78,
      completedInterviews: 0,
      completedShifts: 0,
      employerFeedbackAvg: 0,
      noShowCount: 0,
      badges: [
        { id: "weekend_avail", title: "Доступна по выходным", icon: "📅" },
        { id: "interview_ready", title: "Готова к интервью", icon: "🎤" },
      ],
      scoreBreakdown: {
        profileCompleteness: 15, languagesAdded: 10, availabilityAdded: 10,
        cvOrAiSummary: 10, fastResponse: 8, completedInterview: 0,
        positiveFeedback: 0, noShowPenalty: 0,
      },
    },
  },
];

// =============================================
// MOCK EMPLOYERS
// =============================================

export const MOCK_EMPLOYERS: (Partial<EmployerProfile> & { name: string; rating: EmployerRating })[] = [
  {
    name: "Cafe Aktau",
    userId: "emp_cafe_aktau",
    businessName: "Cafe Aktau",
    businessCategory: "HoReCa",
    district: "14 мкр",
    telegramUsername: "@cafe_aktau",
    phone: "87771234567",
    hiringNeeds: ["Бариста", "Официант", "Помощник кухни"],
    requiredLanguages: [
      { language: "Русский", level: "fluent", canServeCustomers: true, canWriteMessages: false, canInterview: true },
      { language: "Казахский", level: "conversational", canServeCustomers: true, canWriteMessages: false, canInterview: false },
    ],
    rating: {
      trustScore: 86,
      level: "trusted",
      responseRate: 92,
      averageResponseTime: 18,
      candidateFeedbackAvg: 4.6,
      vacancyCompletenessAvg: 92,
      complaintCount: 0,
      verifiedContact: true,
      scoreBreakdown: {
        verifiedContact: 15, completeProfile: 15, vacancyCompleteness: 20,
        fastResponse: 15, positiveFeedback: 16, freshnessConfirmations: 5,
        complaintsPenalty: 0,
      },
    },
  },
  {
    name: "Nura Store",
    userId: "emp_nura_store",
    businessName: "Nura Store",
    businessCategory: "Retail",
    district: "29 мкр",
    telegramUsername: "@nura_store",
    phone: "87779876543",
    hiringNeeds: ["Продавец", "Кассир"],
    requiredLanguages: [
      { language: "Русский", level: "fluent", canServeCustomers: true, canWriteMessages: true, canInterview: true },
    ],
    rating: {
      trustScore: 74,
      level: "verified",
      responseRate: 75,
      averageResponseTime: 60,
      candidateFeedbackAvg: 4.0,
      vacancyCompletenessAvg: 81,
      complaintCount: 1,
      verifiedContact: true,
      scoreBreakdown: {
        verifiedContact: 15, completeProfile: 15, vacancyCompleteness: 16,
        fastResponse: 10, positiveFeedback: 12, freshnessConfirmations: 6,
        complaintsPenalty: 0,
      },
    },
  },
  {
    name: "AutoWash 7",
    userId: "emp_autowash7",
    businessName: "AutoWash 7 мкр",
    businessCategory: "Service",
    district: "7 мкр",
    telegramUsername: "",
    phone: "87770001122",
    hiringNeeds: ["Автомойщик", "Помощник"],
    requiredLanguages: [],
    rating: {
      trustScore: 61,
      level: "basic",
      responseRate: 55,
      averageResponseTime: 180,
      candidateFeedbackAvg: 3.2,
      vacancyCompletenessAvg: 65,
      complaintCount: 2,
      verifiedContact: false,
      scoreBreakdown: {
        verifiedContact: 0, completeProfile: 10, vacancyCompleteness: 13,
        fastResponse: 8, positiveFeedback: 10, freshnessConfirmations: 5,
        complaintsPenalty: -15,
      },
    },
  },
];
